export const JSON_API_ROCKETS = "http://localhost:8000/rockets";

export const ACTIONS = {
  GET_PRODUCTS: "GET_PRODUCTS",
  GET_PRODUCT_DETAILS: "GET_PRODUCT_DETAILS",
  GET_CART: "GET_CART",
  AUTH_SUCCESS: "AUTH_SUCCESS",
  AUTH_LOADING: "AUTH_LOADING",
  AUTH_ERROR: "AUTH_ERROR",
  CLEAR_AUTH_STATE: "CLEAR_AUTH_STATE",
  AUTH_LOGOUT: "AUTH_LOGOUT",
};

export const PRODUCT_LIMIT = 3;
